# Abstract {-}

*Pseudocaranx georgianus* is a commercially important fishery in New Zealand. Currently, the management of this fishery assumes that Quota Management Areas comprise single biological stocks of a single species. However, little is known regarding the population structure of New Zealand *P. georgianus* and morphological data suggests that a cryptic *Pseudocaranx* species is included within these fisheries. 

Whole genome sequence data was used to assemble and describe the first *P. georgianus* mitogenome. Primers were developed to produce the first genetic sequence data for New Zealand *P. georgianus*. The cytochrome c oxidase subunit I (COI) gene was sequenced for fourteen *P. georgianus* from New Zealand waters. These were compared phylogenetically with existing COI sequence data for *P. georgianus* from Australia and other *Pseudocaranx* species from a world-wide distribution. The hyper-variable control region of 304 *P. georgianus* sampled throughout New Zealand's North Island and 68 *P. georgianus* from three locations in Western Australia were also sequenced. These sequences were used to explore the population structure and demographic history of New Zealand *P. georgianus* using haplotype networks, AMOVA's, genetic diversity measures, Tajima's D, Fu's F and Bayesian migration analyses.

The *P. georgianus* mitogenome is typical of Cartilaginous fish species showing no major gene rearrangements, typical gene region lengths and stop and start codons. While assembling the *P. georgianus* mitogenome, this thesis demonstrates the importance of key methodological choices made when assembling mitogenomes from whole genome sequence data in silco in Geneious version 11.1. The choice of reference mitogenome has the largest influence on the quality of the assembly, impacting the annotation of the final mitogenome and the resolution of uncertain DNA regions. Increasing the number of mapping iterations increased the quality of the assembly but has a limited ability to mitigate the effects of using a poor reference mitogenome. Overall, I demonstrate the need to investigate and report the quality of published mitogenomes. 

All *Pseudocaranx* species were monophyletic on the COI gene, supporting the current taxonomy of the *Pseudocaranx* complex. *P. georgianus* from Western Australia and New Zealand's North Island represent a monophyletic clade pending a taxonomic verification that two *Pseudocaranx dentex* sampled in Australia are in fact *P. georgianus*. 

No evidence was found to suggest that either of the New Zealand or Western Australian populations of *P. georgianus* are isolated by distance or clearly structured as distinct stocks. However, some populations of New Zealand *P. georgianus* were genetically distinct, including fish sampled from Raglan and the Bay of Plenty ($F_{ST}$ of 0.02698 ($p$-value: 0.00901+-0.0091) as well as the North Cape and North Taranaki Bight ($F_{ST}$: 0.02698, $p$-value: 0.00901+-0.0091).

Some evidence was found to support the claim that *P. georgianus* along the west coast of New Zealand's North Island is structured and no evidence was found to refute the claim that fish from the Bay of Plenty are the same biological stock as fish from TRE2. Highly divergent control region sequences of fish sampled from Three Kings Islands and the Kermadec Islands suggest that these fish could be a species distinct from *P. georgianus*. Two genetically distinct populations of *P. georgianus* were identified in New Zealand's North Island and Western Australia ($F_{ST}$: 0.03517, $p$-value < 0.001), but further research would be required to determine if they are distinct species or populations. One juvenile population sampled in Whangarei had a high level of genetic connectivity with adult *P. georgianus* throughout New Zealand's North Island, likely reflecting the batch spawning and occasional long-distance migration behaviour of *P. georgianus*.

Negative Tajima's D and Fu's F statistics ($D$: -1.50612, $p$-value: 0.018; $F$: -23.54376, $p$-value: 0.011), unimodal mismatch distributions and skyline plots indicate that the New Zealand *P. georgianus* population has undergone a population expansion, possibly resulting from a geographic range expansion. The Western Australian population may also have undergone a population expansion ($D$: -1.27903, $p$-value: 0.086; $F$: -24.11497, $p$-value < 0.00001). However, a multimodal mismatch distribution (Harpending's Raggedness index: 0.00454591, $p$-value: 0.02) indicated that there is some stability in the size of this population. 

This thesis is a first genetic investigation into New Zealand *P. georgianus* and has provided important biological insights into this species. Valuable information is revealed which will inform the management of New Zealand *P. georgianus* fisheries as inputs for stock assessment models. Additionally, several future research directions have been revealed which will further extend our knowledge of this taonga. For example, future genetic and taxonomic analyses may reveal a cryptic *Pseudocaranx* species occurring in the Three Kings and Kermadec Islands.

# Interactive RShiny app {-}

```{r echo = FALSE, fig.cap = "An R Shiny app displaying a few key results of this thesis. Interact further at: https://leahkemp.shinyapps.io/trevallyapp/."}
knitr::include_app("https://leahkemp.shinyapps.io/trevallyapp/")
```