# Chapter six: General discussion {#generalDiscussion}

This thesis is a first genetic investigation into New Zealand *P. georgianus*. Investigating the evolutionary relationships and population genetics of this key fisheries species has provided important biological and fisheries management insights regarding the taxonomy of the *Pseudocaranx* genus, the population structure and demographic history of New Zealand *P. georgianus*. Additionally, it has provided a valuable basis from which genetic or genomic tools can be applied to this or other fishery species in the future.

This thesis has contributed to the growing species "bar-coding" database (@Ward2009) by producing the first COI sequences published for New Zealand *P. georgianus*. This contribution to a straightforward and standardised database allows for easy comparisons to the results of older genetic studies. The first control region sequence data has been produced for New Zealand *P. georgianus*, providing genetic data that can be reanalysed or extended in future research. Furthermore, the utility of two mitochondrial gene regions, the COI gene and the control region, for investigating the phylogenetics and population genetics of New Zealand *P. georgianus* has been demonstrated.

## Key findings

### *P. georgianus* mitogenome

The first *P. georgianus* mitogenome is assembled and described in this thesis. The *P. georgianus* mitogenome was found to be typical of ray-finned and cartilaginous fish in terms of its overall structure, gene region lengths and stop and start codons.

Using the assembly of the *P. georgianus* mitogenome from whole genome data in silico as an example, I demonstrated the influence a few key methodological choices have on the quality of mitochondrial data as well as some subtleties in how the assembly algorithm handles real life data. The most important determinant of mitogenome quality was the choice of reference mitogenome used in the assembly process, impacting the annotation of the final mitogenome and the resolution of uncertain regions.

I highlighted that mitogenomes of a taxonomically closely related species does not guarantee a robust mitogenome assembly. Instead, the reference mitogenome that is genetically similar is required. Furthermore, the level of genetic similarity of the reference genome required for a robust mitogenome will vary by DNA region due the differing mutational rates along mitogenomes.

The number of mapping iterations used in the assembly process also had an important impact on the quality of the assembly. Using a sufficient number of mapping iterations improved the coverage and identity of more difficult to resolve regions. However, a large number of mapping iterations was unable to mitigate the effects of choosing a poor reference mitogenome and could increase the incorporation of sequencing errors.

Overall, this investigation into a few key methodological choices during the assembly of mitogenomes from whole genome data in silico provides a reminder to keep a genetic perspective when dealing with genetic data, investigate the quality of the assembly and report confidence in mitogenome data produced using these methods. 

### Evolutionary relationships of *Pseudocaranx* species and population genetics of *P. georgianus*

#### *Pseudocaranx* species occurring in New Zealand

The COI gene supported the current taxonomy of the *Pseudocaranx* genus pending taxonomic verification that the naming of two specimens sampled in Australia as *P. dentex* have not been updated (to *P. georgianus*) since the taxonomic revision of the *Pseudocaranx* genus by @Smith-Vaniz2006. In both maximum likelihood and Bayesian phylogenies, *P. georgianus* from New Zealand and Western Australia are monophyletic, indicating that they are the same species.

In contrast, the more variable control region identified a small, but significant genetic difference between *P. georgianus* in New Zealand and *P. georgianus* in Western Australia ($F_{ST}$: 0.03517, $p$-value <0.001). Unfortunately, genetic data is unable to differentiate between common ancestry and ongoing gene flow. Hence, it remains unknown if this genetic difference indicates that these fish are distinct species or sub-populations. 

The literature suggests that a cryptic *Pseudocaranx* species occurs off the North Cape of New Zealand (see Section \@ref(taxonomyIntroductionCrypticSpecies)). No evidence was found on the COI gene or control region of fish sampled in this region to suggest a species distinct from *P. georgianus* is occurring close to the coast of New Zealand's North Cape. However, all five fish that were sampled in the Three Kings Islands and the Kermadec Islands were highly genetically divergent from *P. georgianus* sampled from the rest of New Zealand as well as Western Australia and these fish could represent the cryptic species described in the literature. 

### Population structuring of *P. georgianus* in New Zealand

There was no clear evidence to suggest *P. georgianus* in New Zealand are structured as distinct populations nor isolated by distance. This possibly reflects their batch spawning behaviour and capability for long distance migrations (see Section \@ref(generalIntroductionBiology)). However, due to the large geographic range that *P. georgianus* occupies and the genetic difference identified between New Zealand and Western Australian populations, there could be isolation by distance on a broader scale throughout Australasia.

This thesis provided additional support for putative sub-stocks of *P. georgianus* in New Zealand (see Section \@ref(popStructureNZ)). No evidence was found to refute the claim that *P. georgianus* in the Bay of Plenty are the same biological stock as fish from TRE2. There appears to be some genetic structuring of *P. georgianus* within TRE7 (on the West Coast of New Zealand's North Island), however, the exact structure of these populations was not able to be resolved.

## Combining molecular genetics with morphological data

The taxonomy of the *Pseudocaranx* genus has been difficult to resolve, partly as a result of a historical reliance on morphology to inform the taxonomy of this genus. For contentious taxa such as *Pseudocaranx*, phylogenetic analyses provide further data to compliment morphological data. For the *Pseudocaranx* genus, the genetic data supported the taxonomic groupings produced from morphological analysis by @Smith-Vaniz2006. 

Because the taxonomic groupings of the *Pseudocaranx* genus was supported by the genetic data produced in this thesis, it is likely that morphology would be informative for future taxonomic studies of other *Pseudocaranx* species. It is also likely that such studies would result in the description of new species given the success of describing new *Pseudocaranx* species when research is undertaken (see @Smith-Vaniz2006; @Yamaoka1992). However, there remains some among-species overlap in morphological characters (see @James1974; @Masuda1995; @Smith-Vaniz2006; @Yamaoka1992) and the possibility that environmental factors affect *Pseudocaranx* morphology (see @Masuda1995). Therefore, morphological analyses would benefit from being complimented with phylogenetic analyses to provide a robust taxonomic description of the *Pseudocaranx* complex.

The fact that the genetic data supported prior taxonomic studies based on morphology highlights the value of such morphological analyses. However, there remains a place for genetics to validate taxonomy based on morphological analyses and identify evolutionary events that may obscure the results, such as convergent evolution. It appears that the best course of action is to integrate the two disciplines. 

## Population connectivity of *P. georgianus*

There is some information on the movements of other *Pseudocaranx* species or *P. georgianus* in Australia (see @Afonso2009; @Fairclough2011; @Fowler2018), however relatively little is known regarding the movements of New Zealand *P. georgianus*. Investigating the population genetics of New Zealand *P. georgianus* has, as a by-product, provided some information on the movements of these fish. 

Genetically, *P. georgianus* from very broad geographic regions in New Zealand were highly genetically similar. This occurs over geographic regions broader than the level of movement described in the literature (see Section \@ref(generalIntroductionMovement)). It appears that the level of movement of New Zealand *P. georgianus* might be underestimated by a tag-recapture study undertaken on New Zealand *P. georgianus* [@James1980]. The geographic remoteness of *p. georgianus* has already been overestimated for this species as outlined by @James1974. Little is known regarding the capacity for *P. georgianus* to undertake long-distance movements. However, the level of genetic connectivity of *P. georgianus* over a vast geographic range suggests that *P. georgianus* may have a strong long distance dispersal capacity. This highlights the importance to not assume that there is no gene flow between geographically remote populations. This is particularly important for managing fisheries where a species geographic range covers different jurisdictions, such as *P. georgianus* fisheries in New Zealand and Australia.

## Putting research into practice

### Inputs for fisheries stock assessment models

Fish sampled from the Three Kings and the Kermadec Islands likely represent a species distinct from *P. georgianus*, possibly *P. wrighti*. Measures should be put in place to ensure this population/species is not included in the total allowable catch (TAC) of TRE1 and is accounted for in TRE1 stock assessments. The specimens held in the Te Papa fish collection should be taxonomically identified and genetically sequenced. The results of this thesis suggest that *P. georgianus* from TRE1 and TRE2 are the same biological stock and the genetic data supports the decision to combine these fisheries management boundaries in future stock assessments (see @MPI2018). The population structure of TRE7 is less obvious, given the low sample size of *P. georgianus* from South Taranaki Bight. However, the results support the decision to further investigate the stock structure of *P. georgianus* from the west coast of the North Island (TRE7) (see @MPI2018). Importantly, no data is available for the stock structure of *P. georgianus* from New Zealand's South Island, comprising the TRE3 QMA. The commercial fishing intensity of this region is low, however the level of gene flow between *P. georgianus* in the South Island and North Island of New Zealand has important implications on the overall genetic stability of New Zealand *P. georgianus* fisheries.

If future research shows that *P. georgianus* in Australia and New Zealand are indeed the same species or the same population, the New Zealand and Australian *P. georgianus* fisheries may be best managed as a single fishery to ensure the sustainability of these genetically interacting fisheries. Unfortunately, this study does not provide information on the genetic connectivity of *P georgianus* from Southern and Eastern Australia encompassing the Commonwealth Trawl and Scalefish Hook Sector [@CommonwealthFishery] and the Norfolk Island Fisheries [@NorfolkFishery] with *P. georgianus* from New Zealand. Therefore, further research would be needed to determine if *P. georgianus* from these fisheries are the same or different species or populations as the New Zealand *P. georgianus* fisheries. 

### PCR primers for metabarcoding *Pseudocaranx* species

New Zealand manages *Pseudocaranx* fisheries based on the assumption that a single species and single population is included in each QMA [@MPI2018]. However, *Pseudocaranx* species are not easily distinguished morphologically (\@ref(taxonomyIntroductionRelianceMorpholohy)). *Pseudocaranx* morphology changes with age (@Smith-Vaniz2006) which has already caused taxonomic confusion in the literature [@James1974]. The only morphological feature that is clearly distinct with no overlap between *Pseudocaranx* species is vertebrae counts (@Smith-Vaniz2006) which is not necessarily easy to quantify, especially if the fish needs to remain alive (eg. aquaculture broodstock). On top of this, there remains some question whether this feature is clearly distinct between *Pseudocaranx* species or could be influenced by environmental variables (@Masuda1995). 

This could present challenges when identifying cryptic species that are included in *P. georgianus* fisheries. The *P. georgianus* mitogenome as well the primers and associated PCR protocols developed in this thesis provide an opportunity to develop PCR primers to metabarcode *Pseudocaranx* species like what has been done by @Miya2015. The control region has already been shown to be capable of delimiting *P. georgianus* and *P. wrighti* [@Bearham2004] and could address the practical challenge of delimiting *Pseudocaranx* species in research, fisheries management and aquaculture.

## Inferences based on two mitochondrial markers

Mitochondrial DNA studies have been a fundamental component of population genetic research for several decades [@Ballard2004]. However, in more recent years, some limitations of mitochondrial DNA markers have come to light. This included the presence of mitochondrial recombination in some species (eg. @Burzynski2003; @Davila2011; @Leducq2017), the limitations of testing for isolation by distance [@Teske2018], introgression and direct or indirect selection on mitochondrial DNA markers [@Ballard2004] and its inability to inform male migration or gene flow [@Waples2008]. This has raised questions on the appropriateness of a heavy reliance on mitochondrial DNA markers in phylogenetic and population genetic studies.

There are also limitations associated with using a limited number of DNA markers in phylogenetic and population genetic analyses. Phylogenetic incongruence can occur as a result of different signals held on different DNA markers [@Shen2017] and different markers are appropriate for different purposes [@Hellberg2009].

A thorough review of the literature outlining the limitations of using a few mitochondrial DNA markers is beyond the scope of this thesis. However, this emerging awareness in the literature of some of these limitations highlights the benefit of using additional genetic markers or undertaking genomics in studies extending the work of this thesis. This will provide more power to tackle complex questions and further investigate ambiguous results regarding the phylogenetics and population genetics of *P. georgianus*.

In recent years, there has been a growing interest using genetic tools to inform the biology and in turn the management of New Zealand fisheries [@Bernatchez2017]. There is an ongoing transition from low-resolution genetic studies towards genomics. More data produced using phylogenomics will not be a silver bullet for addressing issues that have come to light in mitochondrial and single gene studies [see @Philippe2011resolving; @Philippe2011difficult; @Springer2018], but it does have the power to address a more comprehensive spectrum of fisheries needs [@Bernatchez2017]. Genomic tools have been underutilised in fisheries despite its ability to inform fisheries management, aquaculture, biosecurity [@Bernatchez2017] and systematics [@Pyron2015]. Typically, a few genetic markers will provide enough resolution for population genetic studies [@Bernatchez2017] since phylogenetic signals are typically strong over sampled loci [@Pyron2015]. However, genomics has the advantage of identifying markers that are informative for the research question at hand [@Bernatchez2017].  

## Future research directions

This thesis is based on two mitochondrial DNA markers. Although such studies have their limitations, it provides a first look into the phylogenetics and population genetics of this key fishery species for which no genetic work has been undertaken. The results of this thesis highlight possibly fruitful areas of study that can be targeted with additional genetic markers or genomics. By investigating the within-species variation along the length of the *P. georgianus* mitogenome, several species-specific gene-region targets have been described, providing a basis from which biologically informative mitochondrial DNA regions can be identified and targeted with PCR. 

For *P. georgianus*, genomics could be used in the description of the cryptic species occurring in the Three Kings and Kermadec Islands. It could also provide a higher-level of resolution to investigate the ambiguous population structure of *P. georgianus* within TRE7 on the west coast of New Zealand's North Island. Moreover, genomics could help distinguish whether *P. georgianus* in New Zealand and Australia are the same species. As is often the case in ecology, scale is important. There was a higher than expected level of genetic connectivity, or panmixia, of *P. georgianus* within and between Australia and New Zealand. This suggests that future studies could benefit from capturing a broader geographic range than was sampled in this study.

The production of the *P. georgianus* mitogenome also provides the opportunity for it to be used as a reference mitogenome to assemble the mitogenomes of other *Pseudocaranx* species. This provides the opportunity to undertake a first genetic investigation into other fisheries species, like what has been done in this thesis. For example, *P. wrighti* is another commercially important fisheries species in Australia [@AFMA2010; @CommonwealthFishery] for which little genetic work has been undertaken. Overall, this thesis has contributed to the wider effort to apply genetic tools to fishery species.

The large majority of the tissues sequenced in this thesis, as well as further tissues that were not sequenced (see Section \@ref(fieldAndLab)) are held in long-term storage. This provides the opportunity to undertake a genomic study of *P. georgianus*, allow further genetic sequencing of other DNA markers or undertake additional sequencing of the COI gene and control region of *P. georgianus*. These tissues could also act as a basis from which to undertake serial sampling of *P. georgianus* which would enable researchers to account for seasonal and annual movements of *P. georgianus*. Such research will further extend our knowledge of the population structure, connectivity, movement and reproductive behaviour of *P. georgianus*, all of which contribute to New Zealand's goal of sustainably harvesting *P. georgianus*.